# Fairness Audit

Miniature starting point for the Jigsaw unintended bias project.

Goal: compare toxicity scores for counterfactual sentences where only one identity term changes.

## 1. Setup

In [1]:
from pathlib import Path

import pandas as pd

DATA_PATH = Path("../data/train.csv")
SAMPLE_SIZE = 5000

## 2. Load a small sample

In [2]:
df = pd.read_csv(DATA_PATH, usecols=["comment_text", "target"], nrows=SAMPLE_SIZE)
df.head()

     target                                       comment_text
0  0.000000  This is so cool. It's like, 'would you want yo...
1  0.000000  Thank you!! This would make my life a lot less...
2  0.000000  This is such an urgent design problem; kudos t...
3  0.000000  Is this something I'll be able to install on m...
4  0.893617               haha you guys are a bunch of losers.

In [3]:
df["target"].describe()

count    5000.000000
mean        0.069611
std         0.158972
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: target, dtype: float64

## 3. Identity terms for counterfactual testing

In [4]:
identity_terms = {
    "religion": ["christian", "muslim", "jewish"],
    "gender": ["man", "woman"],
    "sexuality": ["straight", "gay"],
    "race": ["white", "black", "asian"],
}

identity_terms

{'religion': ['christian', 'muslim', 'jewish'],
 'gender': ['man', 'woman'],
 'sexuality': ['straight', 'gay'],
 'race': ['white', 'black', 'asian']}

## 4. Create counterfactual sentences

In [5]:
def make_counterfactuals(template: str, terms: list[str]) -> pd.DataFrame:
    """Fill a sentence template with identity terms."""
    rows = []
    for term in terms:
        rows.append({
            "identity_term": term,
            "sentence": template.format(identity=term),
        })
    return pd.DataFrame(rows)


template = "I had a conversation with a {identity} person yesterday."
counterfactuals = make_counterfactuals(template, identity_terms["religion"])
counterfactuals

  identity_term                                           sentence
0     christian  I had a conversation with a christian person y...
1        muslim  I had a conversation with a muslim person yest...
2        jewish  I had a conversation with a jewish person yest...

## 5. Placeholder: train our TF-IDF Logistic Regression model

Later we can add:

- `TfidfVectorizer`
- `LogisticRegression`
- train/test split
- toxicity score predictions for the counterfactual sentences

In [6]:
# TODO: Train baseline model here.
# Suggested next packages: scikit-learn, lime.

def score_with_local_model(sentences: list[str]) -> list[float]:
    raise NotImplementedError("Train the TF-IDF Logistic Regression model first.")

## 6. Placeholder: score with Perspective API

Later we can call the API here and store scores in a separate column.

In [7]:
# TODO: Add Perspective API scoring here.

def score_with_perspective_api(sentences: list[str]) -> list[float]:
    raise NotImplementedError("Add Perspective API key and request code first.")

## 7. Placeholder: compare score differences

The core audit table should eventually look like this: one row per counterfactual sentence, with scores from each model.

In [8]:
audit_results = counterfactuals.copy()
audit_results["local_model_score"] = pd.NA
audit_results["perspective_score"] = pd.NA

audit_results

,identity_term,sentence,local_model_score,perspective_score
0,christian,I had a conversation with a christian person y...,<NA>,<NA>
1,muslim,I had a conversation with a muslim person yest...,<NA>,<NA>
2,jewish,I had a conversation with a jewish person yest...,<NA>,<NA>